name: myproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  convex_bottom_bar: 
  curved_navigation_bar: 
  image_picker:  # สำหรับการเลือกและถ่ายภาพ
  cupertino_icons: 
  url_launcher: 
  intl: 
  animated_text_kit: 
  lottie: 
  provider: 
  font_awesome_flutter: 
  flutter_animated_icons: 
  shimmer: 
  flutter_spinkit: 
  awesome_dialog: 
  google_fonts: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 

flutter:
  uses-material-design: true

  # เพิ่ม assets ที่ต้องการใช้งาน (เช่นโฟลเดอร์ images)
  assets:
    - images/QR.png
    - images/logohorplus.png
